### ISSUE TITLE
Apply to join TripAdvisor GitHub community

### ISSUE THREAD

**Issue by tjcchen** [jonross/peggy#1]
Hi Jonathan,

I know this is not the correct way to connect with TripAdvisor GitHub community. But I think at least a member in TripAdvisor organization could see my message.

I formerly worked for TripAdvisor China team based in Beijing. My employee ID is: 34886. I have to say TripAdvisor is a great company in helping travelers around the globe. Even though I have left my position to pursue my Master's Degree in Northeastern University, MA, I still keep watching TripAdvisor's new features in helping other people. I am writing to you to query that could I apply to join TripAdvisor GitHub community, or could you please provide me with some instructions to achieve this goal. Thanks in advance!

I love open source, love writing code, and hope to make contributions to TripAdvisor OSS community.

Thanks,
Andy Chen

**Comment by jonross** [comment]
Hi Andy,
Sorry but I'm no longer with TripAdvisor.

**Comment by tjcchen** [comment]
Ok, sorry for disturbance, Jonathan. Still say thank you to your kind help!
